### ISSUE TITLE
More EPG than just now and next?!

### ISSUE THREAD

**Issue by ClashC** [rofafor/vdr-plugin-iptv#6]
Hello,

I like this plugin very much. It works very reliably. I have a few more questions.
—> EIT scanning functionality is disabled by default. (Readme)
How can I activate it completely? I want more EPG, at least for 1 or 2 days. 
How can I create 2 x IPTV devices? 1 device for LiveTV and the 2 device for one recording. Or is that not necessary?

Best regards

**Comment by rofafor** [comment]
1) EIT scanning means that VDR is actively tuning into transponders while device are idling. I found this quite nasty within network streams and limited bandwidth, but you can enable it by modifying the return value of ```cIptvDevice::ProvidesEIT``` in device.c. Notice, that fetching EIT data from currently tuned channel should work, if the channel is configured correctly (nid/tid/sid fields) and the IPTV stream is providing the EIT table. Otherwise, you'll need to use some external EPG sources and plugins.

2) Define the number of devices via command-line: ```-P "iptv -d 2"```
